// Goldie Street – build sequence.
// Source: RWC Construction Methodology Rev C, Concrete Phase Methodology Rev 6,
// Detailed Programme Rev C and Site Logistics & Phasing Rev C (Aug 2026).
// Durations are the programme's indicative planning dates, not a contract CPM.

export const PROJECT = {
  name: 'Goldie Street',
  subtitle: 'Vellenoweth Green Residences',
  address: '10–14 Goldie Street, St Heliers, Auckland',
  summary: '5 terrace houses over a full-site basement carpark · 2,634 m² GFA · 1,364 m² site',
  start: '2026-06-29',
  pc: 'Oct/Nov 2027',
};

// pkg: which package / trade leads the stage
export const PACKAGES = {
  CLL: 'CLL · Stage 1 in-ground & undercroft',
  CON: 'Concretec · precast superstructure',
  LB: 'Lindsay Building · envelope & fitout',
  SVC: 'Services subtrades',
  ALL: 'Whole project',
};

export const STAGES = [
  {
    id: 'est', pkg: 'CLL', wk: '1–2', start: '2026-06-29', end: '2026-07-10',
    title: 'Site establishment, ESC & piling platform',
    what: 'Take possession of the cleared site (demolition By Owner). Fence the site with gates at the south entry and north exit, set up the compound and wheel-wash, install erosion & sediment controls before ground is opened, and build the certified GAP65 piling platform.',
    qty: ['Goldie St drive-in bays taken as the TMP works zone: crane standing, unloading & skips', 'Silt fence ~120 lm, 2 sumps, wheel-wash at exit', 'GAP65 platform ~350 m² × 300 on geotextile', 'Movement pins @ 10 lm on the wall line'],
    holds: ['ESC signed off before earthworks', 'Platform proof-roll + TW certificate before rig mobilises', 'SLR baseline + condition surveys of No. 8 & No. 16 issued'],
    plant: '20 t excavator, roller, tippers', crew: 4,
    crane: 'No crane. Goldie St bays fenced as the works zone. Crane standings are marked in the bays and the TW engineer checks bearing (mats on the concrete bays over the 100 W watermain in the berm: confirm the services are clear of the outrigger pads).',
  },
  {
    id: 'piles', pkg: 'CLL', wk: '2–7', start: '2026-07-06', end: '2026-08-14', milestone: 'MS1 · Site established, piling underway',
    title: 'Secant pile retention wall',
    what: 'Bore the secant wall around the basement perimeter (less the two ramp mouths). Primary (soft) piles are drilled and concreted first; secondary (firm) piles cut into them and carry the cages. Rotary boring only, with no driven casing, to keep vibration down next to No. 8 and No. 16.',
    qty: ['154 piles Ø600 @ 750 crs, 6.5 m avg = 1,001 lm', '77 cages HD25 + R10 spiral = 24.0 t', '283 m³ 35 MPa tremie concrete'],
    holds: ['Pile set-out survey (±25 mm)', 'Cage placement per firm pile', 'Tremie record per pile vs 0.283 m³/m', 'Verticality 1:100 checked on mast'],
    plant: '50 t rotary piling rig + service crane', crew: 4,
    crane: 'Piling rig + its own service crane, on the certified GAP65 platform. Cages are lifted with taglines inside the rig radius + 5 m exclusion zone.',
  },
  {
    id: 'reroute', pkg: 'CLL', wk: '4–7', start: '2026-07-20', end: '2026-08-14',
    title: 'Public WW/SW re-route in Goldie Street',
    what: 'Re-lay the public sewer and stormwater clear of the new crossings under an approved CAR and TMP. One lane and both property accesses stay open. The 100 dia watermain is potholed and stays live.',
    qty: ['45 lm Ø150 uPVC SN16 sewer', '35 lm Ø225 stormwater', '3 × Ø1050 manholes (2 WW, 1 SW)'],
    holds: ['Existing services potholed before digging', 'Air test + CCTV acceptance by council before backfill', 'Compaction tests on reinstatement'],
    plant: '20 t excavator, trench shields, overpump', crew: 4, note: 'Provisional – subject to Watercare / Healthy Waters approval.',
  },
  {
    id: 'dig', pkg: 'CLL', wk: '4–9', start: '2026-07-20', end: '2026-08-28',
    title: 'Bulk excavation – top-down behind the wall',
    what: 'Dig the basement in lifts from the ramp mouths once the wall is 2–3 weeks ahead. Trucks come in at the south crossing, load inside the site and leave at the north crossing, so there is no reversing on Goldie Street. Pumps on auto-start protect the hole from overland flow.',
    qty: ['2,107 m³ bank (1,869 plate + 82 ramps + 156 pool pits)', '~310 truck loads @ 8 m³ to CMP – free disposal', 'Formation +1.32, 837 m² proof-rolled'],
    holds: ['Formation proof-roll witnessed by geotech (T+T)', 'Movement pins read 2× weekly – ALERT 10 mm / ALARM 15 mm'],
    plant: '30 t + 20 t excavators, 8 m³ tippers', crew: 4,
  },
  {
    id: 'capping', pkg: 'CLL', wk: '6–10', start: '2026-08-03', end: '2026-09-04',
    title: 'Capping beam & shotcrete facing',
    what: 'Trim the pile heads and pour the RC capping beam as a continuous waler. As the dig comes down, spray 100 mm shotcrete to the exposed face in lifts with 665 mesh, with drainage strips behind each soft pile.',
    qty: ['Capping beam 600 × 400 = 27.6 m³, 3.6 t reo', 'Shotcrete 100 thk, 40 MPa = 310 m²', 'Vertical drainage strips to wall drain'],
    holds: ['Capping beam reo pre-pour', 'Shotcrete test panel + thickness pins per lift'],
    plant: 'Shotcrete pump & nozzle set, boom pump', crew: 4,
  },
  {
    id: 'drain', pkg: 'CLL', wk: '8–12', start: '2026-08-17', end: '2026-09-18',
    title: 'Private drainage & subsoil under the slab',
    what: 'Lay under-slab foul and stormwater collectors, cesspits and the ACO channels at the ramp feet (the flood defence line). Wall drain at the secant toe and a herringbone subsoil network in the hardfill, all discharging to the duplex sump pumps.',
    qty: ['70 lm foul @ 1:60 (5 house stacks)', '90 lm SW 100–225 + 4 cesspits + 2 ACO channels', '115 lm wall drain + 200 lm herringbone subsoil'],
    holds: ['As-laid survey + CCTV before slab cover', 'Subsoil connectivity test to sump'],
    plant: '8–14 t excavator, laser', crew: 4,
  },
  {
    id: 'tank', pkg: 'CLL', wk: '9–11', start: '2026-08-24', end: '2026-09-11', water: true,
    title: 'Basement tanking, XPS & hardfill',
    what: 'The zero-defect activity. On sand blinding, torch-on Nuraply 3PTM sheet tanking under the whole slab with a 400 mm upstand onto the secant face. Walls get Nuraply 3PG on the shotcrete, protected by Nuradrain board. Then 40 mm XPS and 150 mm hardfill go on the same week to close the exposure window.',
    qty: ['3PTM underslab 815 m² incl upstands', '3PG + Nuradrain to walls 310 m²', 'XPS 40 mm (250 kPa) 769 m² · hardfill 150 + blinding'],
    holds: ['Substrate accepted by applicator', 'Every lap walked & probed (100 side / 150 end)', 'Third-party sign-off + flood / holiday tests before ANY cover'],
    plant: 'Torch sets, 8 t excavator, plate/roller', crew: '3–4 applicator + civil crew',
    defences: [
      ['Membrane', 'Nuraply 3PTM / 3PG, applicator warranty'],
      ['Concrete', 'Crystalline admixture in all 273 m³ below-ground concrete'],
      ['Joints', 'Hydrophilic waterstop + re-injectable hose, 272 lm'],
      ['Pumps', 'Duplex sump pumps, high-level alarms, non-return valves'],
      ['Verification', 'Independent QA at every hold point, 24 h flood tests'],
    ],
  },
  {
    id: 'slab', pkg: 'CLL', wk: '10–15', start: '2026-08-31', end: '2026-10-09',
    title: 'Footings, lift pits & L0 slab (pours 1–4)',
    what: 'Cast footings and ground beams under the precast lines and the 5 lift pits, then pour the 200 mm L0 slab in four ~190 m² zones with a power-float finish. The slab is the finished carpark surface and becomes the site hardstand.',
    qty: ['Footings 160 lm, 38.4 m³ · 5 lift pits 11 m³', 'L0 slab 200 thk, 30 MPa, 154 m³, HD12 @ 200 EW T&B', 'Pour 1 A (gr 1–3) wk12 · 2 B wk13 · 3 C wk13 · 4 D wk14'],
    holds: ['Reo pre-pour on ALL four slab pours', 'Cube sets per pour · flatness checks on float finish'],
    plant: 'Boom pump, 2 power floats', crew: 4,
  },
  {
    id: 'ducts', pkg: 'CLL', wk: '11–13', start: '2026-09-07', end: '2026-09-25',
    title: 'Incoming services trench & ducts',
    what: 'Trench the shared incoming services while the frontage is still open: power, water, gas and comms ducts with marker tape and pits.',
    qty: ['25 lm shared trench 0.6 × 1.2', '2 × Ø100 power, Ø32 water, Ø32 gas, 2 × Ø50 comms'],
    holds: ['Duct proving (mandrel / draw wire) before backfill'],
    plant: '8 t excavator', crew: 4,
  },
  {
    id: 'ramps', pkg: 'CLL', wk: '13–16', start: '2026-09-21', end: '2026-10-16', milestone: 'MS2 · L0 substructure complete (~14 Oct 26)',
    title: 'Entry (S) & exit (N) ramps + flank walls',
    what: 'Cast the two ramp slabs on grade with a broom finish and the insitu flank walls, so the ramps can carry traffic for the precast phase and the one-way flow works.',
    qty: ['2 ramp slabs 180 thk = 68 m², 13 m³', 'Flank walls 200 thk = 53 m², 10.6 m³', 'Pour 5 – wk 15'],
    holds: ['Ramp reo pre-pour'],
    plant: 'Boom pump', crew: 4,
  },
  {
    id: 'undercroft', pkg: 'CLL', wk: '14–15', start: '2026-09-28', end: '2026-10-09',
    title: 'Precast undercroft walls & basement stairs',
    what: 'Once the L0 slab has 7-day strength, a 55 t mobile crane on the slab (on load-spread mats) erects the undercroft wall panels on shims, dowelled into grout tubes and propped, then the 5 precast stair flights.',
    qty: ['26 wall panels 150 thk, 350 m², max 5.1 t', '5 precast stair flights 3.2 t'],
    holds: ['Crane standing / TW sign-off before tracking onto slab', 'Ramp gradient & turning check for the 55 t (south ramp)', 'Grout cubes + dowel record per panel'],
    plant: '55 t mobile on L0 slab', crew: 4,
    crane: "55 t AT drives down the SOUTH ramp onto the cured L0 slab, on mats with TW sign-off. It erects from the NORTH end first and retreats south, so it's never boxed in by its own panels, then backs out up the ramp. Working radius ≤12 m for panels ≤5.1 t. Both ramps stay clear of the tail swing.",
  },
  {
    id: 'pools', pkg: 'CLL', wk: '14–18', start: '2026-09-28', end: '2026-10-30',
    title: 'Pool pits & precast pool shells',
    what: 'Set the 5 precast pool shells in the pool court zone (grid B–A, AD-06). The shells sit in the podium over the rear basement storage, bedded on insitu plinth walls cast off the L0 slab, before the LG planks close over. They are lifted from the Goldie St bays by the mobile crane. The fibreglass lining follows.',
    qty: ['5 shells 3 × 5 × 1.5 m, ~15.1 t each', 'Insitu plinth walls under each shell', 'Fibreglass lining 195 m²'],
    holds: ['LIFT STUDY: ~15 t shells at ~32 m radius – confirm crane size / method', 'Bedding level survey', 'Shell level / plumb before crane release', 'Landscape design frozen BEFORE casting (risk)'],
    plant: '130 t mobile from street', crew: 4,
    crane: 'Shells are ~15 t, and the pool centres are ~31–32 m from the standings in the bays (two set-ups, in front of Houses 1–2 and Houses 4–5). That is beyond a 130 t AT chart at that radius. HOLD: lift study before booking. Options: a ~220–250 t AT in the bays, or bring the shells in through the open basement before the LG planks and set them from a crane on the L0 slab.',
  },
  {
    id: 'lg', pkg: 'CLL', wk: '16–19', start: '2026-10-12', end: '2026-11-06',
    title: 'LG flat slab – first suspended slab + topping',
    what: 'Planks are lifted straight off HPMV trailers by the 130 t mobile working from the street in booked TMP windows, landed on props, then the 75 mm topping is poured in two visits and power floated.',
    qty: ['42 planks 2.4 × 7.4 m, 9.6 t', 'Topping 75 thk, 50.3 m³, SE82 mesh (Pour 6)', 'Props to 2.85 m soffit'],
    holds: ['Lift plan per set-up: outrigger loads on the bays checked clear of the 150 VC sewer', 'Plank seating length per unit', 'Topping pre-pour (mesh, laps, thickness)', 'Cube strength before de-prop → back-props'],
    plant: '130 t mobile (street), boom pump, power floats', crew: 4,
    crane: '130 t AT in the Goldie St bays ONLY, with three set-ups in front of Houses 1–2, House 3 and Houses 4–5. The house planks are within ~26 m. The rear podium planks over the pool court reach ~34 m, so they are lifted as lighter part-width units: check the chart for each set-up. Planks come straight off the HPMV in the closed traffic lane. The footpath is closed and pedestrians escorted in each lift window.',
  },
  {
    id: 'w1', pkg: 'CON', wk: '18–20', start: '2026-10-26', end: '2026-11-13',
    title: 'Party wall panels LG → L1 (exposed face)',
    what: 'The party and end wall panels are lifted by the 130 t AT working from the Goldie St bays, which relocates along the frontage. They have a finished architectural face on one side, so they are handled with soft slings and protected edges. The panels land on shims, are dowelled into grout tubes and stay propped until their floor diaphragm is complete.',
    qty: ['6 party lines · 150 thk panels, max 4.9 t', 'LG +4,610 → L1'],
    holds: ['Grout cubes at EVERY panel base', 'Plumb & line survey before the next lift', 'Agreed sample panel governs finish'],
    plant: '130 t AT in Goldie St bays (3 set-ups)', crew: '4–6',
    crane: 'Street-based: the 130 t relocates along the bays, with set-ups in front of Houses 1–2, House 3 and Houses 4–5. Panels ≤4.9 t at ≤28 m. This REPLACES the 55 t-on-the-LG-deck in the methodology, so no crane is stranded on the deck and no crane loads go into the back-props. Confirm with HFC / Concretec.',
  },
  {
    id: 'l1', pkg: 'CON', wk: '20–23', start: '2026-11-09', end: '2026-12-04',
    title: 'L1 flat slab, balconies & topping (Pour 7)',
    what: 'L1 planks are flown in from the street to booked windows, with the precast balconies and their thermal breaks in the same windows. The 75 mm topping follows, and the level is back-propped before the level above goes up.',
    qty: ['38 planks + infill = 670 m²', '5 balcony units ~8.4 t', 'Topping 50.3 m³, SE82'],
    holds: ['No construction load on topping below 20 MPa', 'Back-props before next level erects'],
    plant: '130 t mobile (street), boom pump', crew: '4–6',
    crane: 'Same three street set-ups as the LG planks. Balconies (~8.4 t) fly in the same windows, at ≤12 m radius.',
  },
  {
    id: 'w2', pkg: 'CON', wk: '21–23', start: '2026-11-16', end: '2026-12-04',
    title: 'Party wall & facade panels L1 → L2',
    what: 'Second lift of party walls, plus the 12 insulated sandwich panels (PIR core) on the northern elevation, in the same cycle.',
    qty: ['Balance of ~78 panels (1,020 m² total)', '12 sandwich panels 180 m² – north elevation'],
    holds: ['Dowel epoxy certification per batch', 'Plumb & line survey'],
    plant: '130 t AT in Goldie St bays (3 set-ups)', crew: '4–6',
    crane: 'Same three street set-ups. North sandwich panels are lifted from the north set-up.',
  },
  {
    id: 'l2', pkg: 'CON', wk: '24–25', start: '2026-12-07', end: '2026-12-18',
    title: 'L2 flat slab, balconies & topping (Pour 8)',
    what: 'L2 planks and the remaining balconies go in, then Pour 8 is placed, targeting completion before the Christmas shutdown.',
    qty: ['30 planks = 525 m²', '5 balcony units', 'Topping 39.3 m³'],
    holds: ['Topping cure records', 'Back-props locked off before the break'],
    plant: '130 t mobile (street), boom pump', crew: '4–6',
    crane: 'Same three street set-ups. The last big crane day is before the Christmas shutdown, then the 130 t demobilises.',
  },
  {
    id: 'xmas', pkg: 'ALL', wk: '26–28', start: '2026-12-18', end: '2027-01-11',
    title: 'Christmas shutdown',
    what: 'Full shutdown. Before the break, every erected panel is grouted or braced, planks are grouted and propped, loose materials are strapped down and the deck is secured for 3 weeks in a High wind zone. The first job back is a full temporary-works and bracing re-inspection.',
    qty: ['18 Dec 2026 – 11 Jan 2027'],
    holds: ['TW & bracing re-inspection on restart'],
    plant: '–', crew: 0,
  },
  {
    id: 'roof', pkg: 'LB', wk: '29–32', start: '2027-01-11', end: '2027-02-05', milestone: 'MS3 · Structure topped out (~Feb 27)',
    title: 'Structural steel, L2 framing & L3 timber roof',
    what: 'Close out toppings and grouting, then erect the steel posts, beams and flitch beams on cast-in embeds. Frame the L2 walls and the L3 roof in timber, with slotted fixings at the timber-to-concrete joints, and fix the 17 mm ply substrate.',
    qty: ['Structural steel ~32 t', 'Prenail L2 walls, LVL / flitch interfaces', '17 mm ply roof substrate'],
    holds: ['Survey close-out of structure', 'Nothing moisture-sensitive below until roof closed'],
    plant: 'Hiab / crane attendance', crew: 6,
    crane: 'Hiab / 60 t city crane in the bays for steel (~32 t, lifts ≤2 t) and roof framing packs, with set-ups in front of Houses 1, 3 and 5.',
  },
  {
    id: 'membrane', pkg: 'LB', wk: '29–34', start: '2027-01-18', end: '2027-02-19',
    title: 'Scaffold + Nuraply 3P membrane roof',
    what: 'Scaffold to the terrace perimeter (AS/NZS 1576, tied to the precast), with loading bays at L1/L2, a goods hoist and a protected pedestrian gantry. The two-layer membrane roof, gutters, flashings, RWOs and overflows go on behind the parapets.',
    qty: ['Scaffold ~11 m high × 37 m frontage, both end walls (over the ramps) and the rear', 'Nuraply 3P two-layer membrane roof'],
    holds: ['Scaffold inspection & tag', 'Membrane ITP – laps, upstands, outlets'],
    plant: 'Goods hoist', crew: 6,
    crane: 'Crane stood down. Goods hoist at the frontage and loading bays at L1/L2 take over.',
  },
  {
    id: 'joinery', pkg: 'LB', wk: '31–35', start: '2027-02-01', end: '2027-02-26', milestone: 'MS4 · WEATHERTIGHT (late Feb 27)',
    title: 'APL joinery → weathertight',
    what: 'APL Architectural Series aluminium joinery (Low-E IGU) with full-height sills into the precast rebates: screwed off, air-sealed and flashed. With the roof closed and the joinery in, the building is weathertight and internal trades start under cover.',
    qty: ['APL Architectural Series, Low-E IGU', 'Glazed pivot entry doors'],
    holds: ['Structure survey before joinery', 'Joinery flashing ITP'],
    plant: 'Hoist, Hiab', crew: 6,
  },
  {
    id: 'facade', pkg: 'LB', wk: '36–57', start: '2027-03-01', end: '2027-07-30',
    title: 'Facade – Sto render, GRC & Nu-Wall',
    what: 'Behind weathertight: cladding prep, RAB and cavity battens, then the Sto render system, GRC feature panels (allowing two resubmit cycles) and Nu-Wall/ArchiMax profiled aluminium. Everything is coastal-specified for corrosion zone D.',
    qty: ['Sto plaster render system', 'GRC feature panels', 'Nu-Wall / ArchiMax aluminium, Abodo soffits'],
    holds: ['GRC shop drawings / samples approved', 'Cavity & flashing inspection before render'],
    plant: 'Scaffold, hoist', crew: 8,
  },
  {
    id: 'doors', pkg: 'LB', wk: '49–59', start: '2027-06-01', end: '2027-08-13',
    title: 'Carpark door & glass balustrades',
    what: 'Metalbilt ARA perforated carpark doors with number-plate recognition, and Viridian frameless glass balustrades to the balconies.',
    qty: ['Metalbilt ARA carpark doors + automation', 'Viridian frameless glass balustrades'],
    holds: ['Balustrade load test / PS3'],
    plant: 'Hiab', crew: 4,
  },
  {
    id: 'services', pkg: 'SVC', wk: '36–61', start: '2027-03-01', end: '2027-08-27', flow: true,
    title: 'Services rough-in & lifts – House 1 → 5',
    what: 'Rough-in follows weathertight house by house: plumbing & gas, then electrical (Leck), then ducted heat-pump HVAC (Econair). The basement services level carries the carpark extract and shared services. Five Powerglide S-Series lifts go into the surveyed precast shafts.',
    qty: ['5 × Powerglide S-Series 350 kg lifts', '2 × 380 L heat-pump HWC per house', 'UFH & under-tile heating, pool plant'],
    holds: ['Shaft plumb survey vs Powerglide tolerance', 'Pre-line services inspection per house'],
    plant: 'Hoist', crew: 12,
  },
  {
    id: 'fitout', pkg: 'LB', wk: '38–65', start: '2027-03-15', end: '2027-09-24', flow: true,
    title: 'Internal fitout flow-line – House 1 → 5',
    what: 'Each trade finishes House 1 and rolls to House 2. House 1 sets the benchmark for Level 5 plasterboard against exposed concrete, tiling and stone. Order: framing & insulation → linings → Level 5 skim → paint → wet areas & tiling → joinery & stone → floor coverings last.',
    qty: ['Level 5 plasterboard, Resene 3-coat', 'Large-format porcelain tiling', 'Kitchens (KBD) & oak floors By Owner'],
    holds: ['House 1 benchmark sign-off before roll-out', 'Wet-area membrane inspection per house'],
    plant: '–', crew: 20,
  },
  {
    id: 'strike', pkg: 'LB', wk: '58–61', start: '2027-08-02', end: '2027-08-27',
    title: 'Scaffold strike & facade clean-down',
    what: 'Strike the scaffold in stages as the render, GRC and Nu-Wall finish, then clean down the facade.',
    qty: ['Progressive strike, frontage first'],
    holds: ['Facade snag walk before strike'],
    plant: 'Scaffold crew', crew: 6,
  },
  {
    id: 'extslab', pkg: 'LB', wk: '58–61', start: '2027-08-02', end: '2027-08-27',
    title: 'Externals 1 – fill, block walls & concrete terraces',
    what: 'Once the scaffold is down, the rear courts go on the podium over the basement. Each house has an LG terrace (grid C–B) and a pool court (grid B–A), both at LG level. Lay the 20-series block upstands between the courts and the planter wall on the rear boundary, then pour the in-situ concrete terraces and pool surrounds to falls over the podium waterproofing. The side yards over the basement behind the ramps are done the same way.',
    qty: ['Podium drainage cell & protection over the LG slab waterproofing', '20-series blockwork, corefilled – court upstands & rear planter wall', 'In-situ concrete terraces & patios ~63 m² per house on 25 sand blinding', 'Pool surround slabs ×5'],
    holds: ['Podium membrane flood test & drainage outlets checked before the build-up goes on', 'Block wall reo & corefill inspection', 'Slab falls away from the building (min 1:60)'],
    plant: 'Skid steer, plate compactor, concrete pump', crew: 8,
  },
  {
    id: 'extpool', pkg: 'LB', wk: '59–63', start: '2027-08-16', end: '2027-09-17',
    title: 'Externals 2 – pools, coping, tiling & pool fencing',
    what: 'Fit out the five pools: plant (pump, filter, heating and LED), stone coping and the outdoor porcelain to terraces and pool surrounds. Then the pool barrier: frameless glass on spigots with self-closing, self-latching gates. The pools are not filled until each barrier is complete and signed off.',
    qty: ['Pool plant ×5 (filtration, heat pump, LED)', 'Stone coping & feature tiling ×5 pools', 'Outdoor porcelain tiles ~90 m² per house', 'Frameless glass pool barrier, 1.2 m high, self-closing gates ×5'],
    holds: ['Pool barrier to NZBC F9: 1.2 m min, gaps <100 mm, latch 1.5 m', 'Council pool barrier inspection BEFORE filling', 'Pool plant commissioning & water balance'],
    plant: 'Small plant', crew: 6, note: 'Pool fencing is required by the Building Code (F9) but is not a separate line in the Estimate Rev A. It is assumed within the frameless glass balustrade allowance. Confirm the scope.',
  },
  {
    id: 'extdeck', pkg: 'LB', wk: '61–64', start: '2027-08-30', end: '2027-09-24',
    title: 'Externals 3 – decks, outdoor kitchens, stairs & garden fences',
    what: 'Vitex decks beside each pool, outdoor kitchens on the LG terraces, and the custom external spiral stairs from each LG terrace to its L2 roof terrace (By Owner). Then the slatted privacy screens between the five courts, and the boundary fences.',
    qty: ['Vitex decking 140×19 ~13 m² per house', 'Outdoor kitchen per house (PS $18k each)', 'External spiral stair with metal balustrade (By Owner)', 'Privacy screens between courts + boundary fences'],
    holds: ['Deck framing inspection (H3.2 / H4 timber, stainless fixings – zone D)', 'Stair balustrade PS3'],
    plant: 'Small plant', crew: 6,
  },
  {
    id: 'extfront', pkg: 'LB', wk: '63–68', start: '2027-09-13', end: '2027-10-15',
    title: 'Externals 4 – driveway, crossings, gates & frontage',
    what: 'The frontage is reclaimed last. Exposed-aggregate driveway and ramp approaches (black oxide), both vehicle crossings and the footpath reinstated to AT standard. Then vehicle gates with number-plate recognition at the head of each ramp, the front wall with pedestrian entry gates and letterboxes, the entry steps up to each LG front door, and the permanent flood barriers at the ramps. The bin store is in the basement (grid 7–8). Last, the works zone is lifted and the drive-in bays are resurfaced, re-marked and handed back as the new on-street carpark.',
    qty: ['Exposed-aggregate driveway ~180 m², black oxide', '2 vehicle crossings + footpath to AT standard', 'Aluminium vehicle gates + NPR ×2, entry gates ×5', 'Entry steps & front paths ×5', 'Flood barriers at both ramp heads'],
    holds: ['Driveway sample board approved 3 wks ahead', 'Crossing & footpath inspection by AT', 'Overland flow / flood protection check (FL +4,610)'],
    plant: 'Concrete pump, small plant, STMS', crew: 8,
  },
  {
    id: 'soft', pkg: 'LB', wk: '65–70', start: '2027-09-27', end: '2027-10-29',
    title: 'Externals 5 – soft landscaping & lighting',
    what: 'Planter soil to the rear planters, side yards and front gardens, then planting, specimen trees in the rear planters and along the frontage, garden lighting and irrigation. The By Owner landscape upgrade follows the landscape architect\'s design.',
    qty: ['Planters, planting & front gardens per house (PS)', 'Specimen trees – rear planters & frontage', 'Garden lighting & irrigation', 'By Owner landscape upgrade'],
    holds: ['Landscape architect walk-through', 'Irrigation test'],
    plant: 'Small plant', crew: 6,
  },
  {
    id: 'pc', pkg: 'ALL', wk: '64–72', start: '2027-09-20', end: '2027-11-12', milestone: 'MS5 · PRACTICAL COMPLETION',
    title: 'Commissioning, CCC & handover',
    what: 'Commission house by house (HVAC, UFH, hot water, pools, lifts and DigiHome), then the shared basement systems. Then WorkSafe lift registration, producer statements, CCC for the Stage 1 and main consents, builder\'s clean, defects and O&M handover.',
    qty: ['5 lift registrations', 'CCC – Stage 1 + main consent', 'PC target Oct/Nov 2027 (client deadline Dec 2027)'],
    holds: ['PS1–PS4 register complete', 'Final council inspections'],
    plant: '–', crew: 10,
  },
];
